### ISSUE TITLE
package installation issue.

### ISSUE THREAD

**Issue by YANGJJ93research** [wilsontom/sRm#23]
Hey, is anyone know why there is an error during the installation of sRm?

`package ‘q3ML’ is not available for this version of R`

Best regards,
Junjie

**Comment by wilsontom** [comment]
Hi Junjie,

Thanks for sending the example file over. I've had a quick look. it looks as if the file contains both spectrum and chromatogram data. Typically MRM would only have chromatogram data. Can you provide more details on the method used to acquire the data ?

Tom
